name: paisasplit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  carousel_slider: ^5.0.0
  http: ^1.2.2
  auto_size_text: ^3.0.0
  swipeable_tile: ^2.0.1
  lottie: ^3.1.2
  loading_indicator: ^3.1.1
  hive:
  hive_flutter:
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.0
  flutter_tesseract_ocr: ^0.4.28
  path_provider: ^2.1.5
  pie_chart: ^5.4.0
  page_transition: ^2.1.0
  google_ml_kit: ^0.19.0
  cupertino_icons: ^1.0.6
  chat_bubbles: ^1.6.0
  blurrycontainer: ^2.1.0
  google_fonts: ^6.2.1
  flutter_gemini: ^2.0.5
  loading_animation_widget: ^1.2.1
  stroke_text: ^0.0.3
  dynamic_background: ^0.1.3
  image_picker: ^1.1.2
  adaptive_action_sheet: ^2.0.3
  flip_card: ^0.7.0
  provider: ^6.1.2
  connectivity_plus: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator:
  build_runner:


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: splash
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Meme
      fonts:
        - asset: assets/fonts/FacultyGlyphic-Regular.ttf
